replicaCount: 3
image:
  repository: cr.yandex/crpn6aaerje2gjt15uh5/docker-image-tvm2360-nginx-test
  tag: 1.0.0
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
