replicaCount: 3
image:
  repository: cr.yandex/crpchbsamuk14ea1q741/docker-image-tvm2360-nginx-test
  tag: 1.0.0
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
