labels: {}

replicas: 1

masterService: ""

image: "cr.yandex/crplnc7jr80hll05i6jc/docker-image-tvm2360-web-proxy"

imageTag: "latest"

imagePullPolicy: "IfNotPresent"

podAnnotations:
  {}

resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

priorityClassName: ""

antiAffinityTopologyKey: "kubernetes.io/hostname"

antiAffinity: "none"

nodeAffinity: {}

nodeSelector: {}

tolerations: {}

restartPolicy: Always

dnsPolicy: ClusterFirst

enableServiceLinks: true

protocol: http

listenHttp: "0.0.0.0"

httpPort: 80

service:
  annotations: {}
  type: ClusterIP
  loadBalancerIP: None
  port: 80
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80

strategy: RollingUpdate

maxSurge: 1

maxUnavailable: 0

securityContext:
  capabilities:
    drop:
      - ALL
  privileged: true
  allowPrivilegeEscalation: true
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 33

terminationGracePeriod: 120

readinessProbe:
  tcpSocket:
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3

livenessProbe:
  tcpSocket:
    port: 80
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 6


nameOverride: ""
fullnameOverride: ""
healthNameOverride: ""

lifecycle: {}

tests:
  enabled: false
