---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-atlantis
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi
